sudo: required
services:
  - docker

before_install:
  - docker build -t cromulentscientist/fib-eb -f ./client/Dockerfile.dev ./client

script:
  - docker run cromulentscientist/fib-eb npm test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "fibonacci-eb"
  env: "FibonacciEb-env"
  bucket_name: "elasticbeanstalk-us-west-2-004190587247"
  bucket_path: "fibonacci-eb"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
